# Sentiment Analysis Prediction

1. Dataset
   ↓
2. Lowercase
   ↓
3. Tokenization
   ↓
4. Stop Words Removal
   ↓
5. Stemming
   ↓
6. Lemmatization
   ↓
7. Clean Text
   ↓
8. TF-IDF
   ↓
9. Train/Test Split
   ↓
10. Logistic Regression
   ↓
11. Prediction
   ↓
12. Accuracy
   ↓
13. New Review Testing

In [1]:
import pandas as pd
import nltk

In [2]:
data = {
    "review": [
        "I love this movie",
        "This movie is amazing",
        "Very good experience",
        "I enjoyed the movie",
        "The product is excellent",
        "I hate this movie",
        "This movie is terrible",
        "Very bad experience",
        "I did not like the movie",
        "The product is horrible"
    ],

    "sentiment": [
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative"
    ]
}

df = pd.DataFrame(data)

df

                     review sentiment
0         I love this movie  Positive
1     This movie is amazing  Positive
2      Very good experience  Positive
3       I enjoyed the movie  Positive
4  The product is excellent  Positive
5         I hate this movie  Negative
6    This movie is terrible  Negative
7       Very bad experience  Negative
8  I did not like the movie  Negative
9   The product is horrible  Negative

In [3]:
print("Number of reviews:", len(df))
print("\nDataset:")
display(df)

Number of reviews: 10

Dataset:

                     review sentiment
0         I love this movie  Positive
1     This movie is amazing  Positive
2      Very good experience  Positive
3       I enjoyed the movie  Positive
4  The product is excellent  Positive
5         I hate this movie  Negative
6    This movie is terrible  Negative
7       Very bad experience  Negative
8  I did not like the movie  Negative
9   The product is horrible  Negative

Text Processing

In [4]:
df["review"] = df["review"].str.lower()

df

                     review sentiment
0         i love this movie  Positive
1     this movie is amazing  Positive
2      very good experience  Positive
3       i enjoyed the movie  Positive
4  the product is excellent  Positive
5         i hate this movie  Negative
6    this movie is terrible  Negative
7       very bad experience  Negative
8  i did not like the movie  Negative
9   the product is horrible  Negative

Tokenization

In [6]:
from nltk.tokenize import word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

df["tokens"] = df["review"].apply(word_tokenize)

df

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

                     review sentiment                           tokens
0         i love this movie  Positive           [i, love, this, movie]
1     this movie is amazing  Positive       [this, movie, is, amazing]
2      very good experience  Positive         [very, good, experience]
3       i enjoyed the movie  Positive         [i, enjoyed, the, movie]
4  the product is excellent  Positive    [the, product, is, excellent]
5         i hate this movie  Negative           [i, hate, this, movie]
6    this movie is terrible  Negative      [this, movie, is, terrible]
7       very bad experience  Negative          [very, bad, experience]
8  i did not like the movie  Negative  [i, did, not, like, the, movie]
9   the product is horrible  Negative     [the, product, is, horrible]

Stop word Removal

In [7]:
from nltk.corpus import stopwords

nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

df["filtered_tokens"] = df["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

df

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,review,sentiment,tokens,filtered_tokens
0,i love this movie,Positive,"[i, love, this, movie]","[love, movie]"
1,this movie is amazing,Positive,"[this, movie, is, amazing]","[movie, amazing]"
2,very good experience,Positive,"[very, good, experience]","[good, experience]"
3,i enjoyed the movie,Positive,"[i, enjoyed, the, movie]","[enjoyed, movie]"
4,the product is excellent,Positive,"[the, product, is, excellent]","[product, excellent]"
5,i hate this movie,Negative,"[i, hate, this, movie]","[hate, movie]"
6,this movie is terrible,Negative,"[this, movie, is, terrible]","[movie, terrible]"
7,very bad experience,Negative,"[very, bad, experience]","[bad, experience]"
8,i did not like the movie,Negative,"[i, did, not, like, the, movie]","[like, movie]"
9,the product is horrible,Negative,"[the, product, is, horrible]","[product, horrible]"

In [ ]:
from nltk.stem import PorterStemmer#Stemming tool

stemmer = PorterStemmer()

df["stemmed_tokens"] = df["filtered_tokens"].apply(
    lambda words: [stemmer.stem(word) for word in words]
)

df

,review,sentiment,tokens,filtered_tokens,stemmed_tokens
0,i love this movie,Positive,"[i, love, this, movie]","[love, movie]","[love, movi]"
1,this movie is amazing,Positive,"[this, movie, is, amazing]","[movie, amazing]","[movi, amaz]"
2,very good experience,Positive,"[very, good, experience]","[good, experience]","[good, experi]"
3,i enjoyed the movie,Positive,"[i, enjoyed, the, movie]","[enjoyed, movie]","[enjoy, movi]"
4,the product is excellent,Positive,"[the, product, is, excellent]","[product, excellent]","[product, excel]"
5,i hate this movie,Negative,"[i, hate, this, movie]","[hate, movie]","[hate, movi]"
6,this movie is terrible,Negative,"[this, movie, is, terrible]","[movie, terrible]","[movi, terribl]"
7,very bad experience,Negative,"[very, bad, experience]","[bad, experience]","[bad, experi]"
8,i did not like the movie,Negative,"[i, did, not, like, the, movie]","[like, movie]","[like, movi]"
9,the product is horrible,Negative,"[the, product, is, horrible]","[product, horrible]","[product, horribl]"

In [ ]:
from nltk.stem import WordNetLemmatizer

nltk.download("wordnet")
nltk.download("omw-1.4")

lemmatizer = WordNetLemmatizer()

df["lemmatized_tokens"] = df["filtered_tokens"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

df
#it will give meaningful baseforms from the clean words

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

,review,sentiment,tokens,filtered_tokens,stemmed_tokens,lemmatized_tokens
0,i love this movie,Positive,"[i, love, this, movie]","[love, movie]","[love, movi]","[love, movie]"
1,this movie is amazing,Positive,"[this, movie, is, amazing]","[movie, amazing]","[movi, amaz]","[movie, amazing]"
2,very good experience,Positive,"[very, good, experience]","[good, experience]","[good, experi]","[good, experience]"
3,i enjoyed the movie,Positive,"[i, enjoyed, the, movie]","[enjoyed, movie]","[enjoy, movi]","[enjoyed, movie]"
4,the product is excellent,Positive,"[the, product, is, excellent]","[product, excellent]","[product, excel]","[product, excellent]"
5,i hate this movie,Negative,"[i, hate, this, movie]","[hate, movie]","[hate, movi]","[hate, movie]"
6,this movie is terrible,Negative,"[this, movie, is, terrible]","[movie, terrible]","[movi, terribl]","[movie, terrible]"
7,very bad experience,Negative,"[very, bad, experience]","[bad, experience]","[bad, experi]","[bad, experience]"
8,i did not like the movie,Negative,"[i, did, not, like, the, movie]","[like, movie]","[like, movi]","[like, movie]"
9,the product is horrible,Negative,"[the, product, is, horrible]","[product, horrible]","[product, horribl]","[product, horrible]"

Clean Text

In [11]:
df["clean_text"] = df["lemmatized_tokens"].apply(
    lambda words: " ".join(words)
)

df

,review,sentiment,tokens,filtered_tokens,stemmed_tokens,lemmatized_tokens,clean_text
0,i love this movie,Positive,"[i, love, this, movie]","[love, movie]","[love, movi]","[love, movie]",love movie
1,this movie is amazing,Positive,"[this, movie, is, amazing]","[movie, amazing]","[movi, amaz]","[movie, amazing]",movie amazing
2,very good experience,Positive,"[very, good, experience]","[good, experience]","[good, experi]","[good, experience]",good experience
3,i enjoyed the movie,Positive,"[i, enjoyed, the, movie]","[enjoyed, movie]","[enjoy, movi]","[enjoyed, movie]",enjoyed movie
4,the product is excellent,Positive,"[the, product, is, excellent]","[product, excellent]","[product, excel]","[product, excellent]",product excellent
5,i hate this movie,Negative,"[i, hate, this, movie]","[hate, movie]","[hate, movi]","[hate, movie]",hate movie
6,this movie is terrible,Negative,"[this, movie, is, terrible]","[movie, terrible]","[movi, terribl]","[movie, terrible]",movie terrible
7,very bad experience,Negative,"[very, bad, experience]","[bad, experience]","[bad, experi]","[bad, experience]",bad experience
8,i did not like the movie,Negative,"[i, did, not, like, the, movie]","[like, movie]","[like, movi]","[like, movie]",like movie
9,the product is horrible,Negative,"[the, product, is, horrible]","[product, horrible]","[product, horribl]","[product, horrible]",product horrible

TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer#text-->num#proccessor,rows(reviews),columns(words)

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df["clean_text"])

print("TF-IDF Shape:", X.shape)

TF-IDF Shape: (10, 13)

In [13]:
from sklearn.model_selection import train_test_split

y = df["sentiment"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (8, 13)
Testing data: (2, 13)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)#tF-IDF,+ -

print("Model training completed!")

Model training completed!

Prediction

In [15]:
predictions = model.predict(X_test)

print("Predicted:", predictions)
print("Actual:", y_test.values)

Predicted: ['Positive' 'Positive']
Actual: <ArrowStringArray>
['Negative', 'Positive']
Length: 2, dtype: str

Accuracy

In [16]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

Accuracy: 0.5
Accuracy Percentage: 50.0 %

#Final Testing

In [ ]:
new_review = ["I really love this movie"]

new_review_tfidf = vectorizer.transform(new_review)#num

prediction = model.predict(new_review_tfidf)

print("Review:", new_review[0])
print("Predicted Sentiment:", prediction[0])

Review: I really love this movie
Predicted Sentiment: Positive